### ISSUE TITLE
Fix current feature list

### ISSUE THREAD

**Issue by Dumpy250** [BF3RM/landing#16]
Current:
![image](https://github.com/BF3RM/landing/assets/83517134/7e4dd777-43f1-4893-afe7-99d54200db08)

- [ ] 80 players should be 64

- [ ] We do not have 24 hour day-night cycles.

- [ ] Mark FROSTBITE ENGINE as completed I guess?

**Comment by kaloczikvn** [comment]
Fixed in aea30dd67ceb578b9e305a867c00c9dcf29092c8
